/**
 * iOS In-App Purchase Configuration for WhatsCard
 *
 * App Store Connect Credentials and Configuration
 *
 * ⚠️ SECURITY WARNING:
 * This file contains sensitive credentials. Never commit to public repositories.
 * Add to .gitignore and use environment variables in production.
 */

export const IOS_IAP_CONFIG = {
  /**
   * App Store Connect Information
   */
  appStoreConnect: {
    appId: '6754809694',
    bundleId: 'com.alittlebetter.better',
    sku: 'WHATSCARD300K',
  },

  /**
   * Subscription Group
   */
  subscriptionGroup: {
    name: 'Premium Access',
    id: '21821977',
  },

  /**
   * Product IDs and Apple IDs
   */
  products: {
    monthly: {
      productId: 'monthly_premium_subscription',
      appleId: '6754809579',
      price: 9.95,
      displayPrice: '$9.95',
      period: 'P1M', // 1 month
      title: 'WhatsCard Premium Monthly',
      description: 'Perfect for trying out',
    },
    yearly: {
      productId: 'yearly_premium_subscription',
      appleId: '6754809873',
      price: 117.99,
      displayPrice: '$117.99',
      period: 'P1Y', // 1 year
      title: 'WhatsCard Premium Yearly - Best Value!',
      description: 'Best value - Save 20%',
      badge: 'BEST VALUE',
    },
  },

  /**
   * Shared Secret for Receipt Validation
   *
   * ⚠️ CRITICAL: Used for server-side receipt verification
   * SECURITY: This secret is now loaded from environment variables
   *
   * The value below is a fallback for development only.
   * In production, you MUST set IOS_APP_STORE_SHARED_SECRET in your environment.
   */
  sharedSecret: process.env.IOS_APP_STORE_SHARED_SECRET || '',

  /**
   * Promotional Offer Configuration
   *
   * Note: Promotional offers require additional setup in App Store Connect:
   * 1. Create subscription offer code
   * 2. Generate subscription key
   * 3. Configure offer with code and discount
   */
  promotionalOffers: {
    WHATSBNI: {
      offerCode: 'WHATSBNI',
      discount: 0.70, // 70% off
      applicableTo: 'yearly_premium_subscription',
      discountedPrice: 35.40, // $117.99 * 0.30
      description: '70% off yearly subscription',
      // Note: Offer ID and signature will be generated by App Store Connect
    },
  },

  /**
   * Sandbox Testing
   */
  sandbox: {
    enabled: __DEV__, // Auto-detect dev mode
    testAccountRequired: true,
  },

  /**
   * Receipt Validation
   */
  receiptValidation: {
    productionUrl: 'https://buy.itunes.apple.com/verifyReceipt',
    sandboxUrl: 'https://sandbox.itunes.apple.com/verifyReceipt',
  },
} as const;

/**
 * Helper function to get product by plan type
 */
export const getIOSProduct = (plan: 'monthly' | 'yearly') => {
  return IOS_IAP_CONFIG.products[plan];
};

/**
 * Helper function to get all product IDs
 */
export const getIOSProductIds = (): string[] => {
  return [
    IOS_IAP_CONFIG.products.monthly.productId,
    IOS_IAP_CONFIG.products.yearly.productId,
  ];
};

console.log('[iOS IAP Config] ✅ Configuration loaded');
console.log(`[iOS IAP Config] App ID: ${IOS_IAP_CONFIG.appStoreConnect.appId}`);
console.log(`[iOS IAP Config] Bundle ID: ${IOS_IAP_CONFIG.appStoreConnect.bundleId}`);
